name: Release CI

on:
    push:
        branches: [master]

env:
    DOCKER_IMAGE: ghcr.io/linkkky/waitlist.api.inssa.club
    VERSION: ${{github.sha}}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out the source code
              uses: actions/checkout@v2
            - name: Setup docker buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - name: Cache docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{runner.os}}-buildx-${{env.VERSION}}
                  resotre-keys: |
                      ${{runner.os}}-buildx-
            - name: Login to ghcr
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{github.actor}}
                  password: ${{secrets.LINKKY_PAT}}
            - name: Build & Push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  builder: ${{steps.buildx.outputs.name}}
                  push: ${{github.event_name != 'pull_request'}}
                  tags: ${{env.DOCKER_IMAGE}}:${{env.VERSION}}

    deploy:
        needs: build
        name: Deploy
        runs-on: [self-hosted, production]
        steps:
            - name: Login to ghcr
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{github.actor}}
                  password: ${{secrets.LINKKY_PAT}}
            - name: Rolling update the service
              run: |
                  docker service update --force --update-parallelism 1 --image ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} inssa_waitlist

    cleanup:
        needs: [build, deploy]
        name: Clean up docker images
        runs-on: [self-hosted, production]
        steps:
            - name: Remove images of older versions
              run: docker rmi $(docker images --filter "before=${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}" --filter=reference="${{ env.DOCKER_IMAGE }}:*" -q)
